local lexers = vis.lexers
background =           '#ffffea'
foreground =           '#000000'
color0 =               '#000000'
color1 =               '#880000'
color2 =               '#005500'
color3 =               '#663311'
color4 =               '#004488'
color5 =               '#770077'
color6 =               '#007777'
color7 =               '#eeeecc'
color8 =               '#eaeaea'
color9 =               '#ffeaea'
color10 =              '#eaffea'
color11 =              '#eeee9e'
color12 =              '#cceeff'
color13 =              '#ffeaff'
color14 =              '#eaffff'
color15 =              '#ffffea'
selection_foreground = foreground
selection_background = color10
cursor =               color11
cursor =               color12
-- cursor =               '#fee92e' -- from material.lua color11
-- cursor =               '#90ece9' -- from vis acme.lua

lexers.STYLE_DEFAULT = 'fore:'..foreground..',back:'..background
lexers.STYLE_NOTHING = ''
lexers.STYLE_CLASS = ''
lexers.STYLE_COMMENT = 'fore:'..color3..',italics,'
lexers.STYLE_CONSTANT = 'bold,italics'
-- DEFINITION and ERROR may need more work but few lexers use them
lexers.STYLE_DEFINITION = 'italics'
lexers.STYLE_ERROR = 'fore:'..color1..',bold'
lexers.STYLE_FUNCTION = 'bold,italics'
lexers.STYLE_KEYWORD = 'bold'
lexers.STYLE_LABEL = ''
lexers.STYLE_NUMBER = 'italics'
lexers.STYLE_OPERATOR = 'bold'
lexers.STYLE_REGEX = 'italics'
lexers.STYLE_STRING = 'italics'
lexers.STYLE_PREPROCESSOR = ''
lexers.STYLE_TAG = 'bold,italics'
lexers.STYLE_TYPE = ''
lexers.STYLE_VARIABLE = ''
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = ''
lexers.STYLE_IDENTIFIER = ''

-- lexers.STYLE_CURSOR = 'fore:'..foreground..',bold,italic'..',back:'..color11
lexers.STYLE_CURSOR = 'reverse'
lexers.STYLE_CURSOR_LINE = 'back:'..cursor
lexers.STYLE_COLOR_COLUMN = 'back:'..color14
lexers.STYLE_SELECTION = 'fore:'..foreground..',back:'..selection_background
lexers.STYLE_STATUS = 'back:'..color14..',fore:'..color3..',bold,italics'
lexers.STYLE_STATUS_FOCUSED = 'back:'..color14..',fore:'..foreground..',italics,bold'
lexers.STYLE_SEPARATOR = ''
lexers.STYLE_INFO = ''
lexers.STYLE_EOF = 'fore:'..color8
